### ISSUE TITLE
Exception "required condition is false: [_nodes containsObject: node]" when I close RTMP stream connection

### ISSUE THREAD

**Issue by mrmda28** [shogo4405/HaishinKit.swift#1454]
### Describe the bug

When I connect to an RTMP stream and playback it, everything is OK. But when I close connection, most of the time the screen freezes.
I found the problem in the **Sources/IO/IOStream.swift** file in the `func tellyUnit(_ tellyUnit: IOTellyUnit, didSetAudioFormat audioFormat: AVAudioFormat?)`. When `audioEngine.detach(tellyUnit.playerNode)` or `audioEngine.disconnectNodeInput(tellyUnit.playerNode)` is called, the exception **"required condition is false: [_nodes containsObject: node]"** appears in nstry (* nstry doesn't always catch it, if nstry doesn't catch it, then the screen freezes).
I'm attaching an archive with a simple demo project, or you can try it on your own using the stream url - "rtmp://streamer1.streamhost.org/salive" and stream name - "hungarian" (I found this stream on the Internet)
[RTMPTest.zip](https://github.com/shogo4405/HaishinKit.swift/files/15458189/RTMPTest.zip)

### To Reproduce

1. Connect to an RTMP stream and playback it
2. Disconnect from the stream (сlose connection)
3. At this point, the screen freezes, if not, repeat steps 1 and 2

### Expected behavior

Connection and disconnection from the stream are working correctly

### Version

tag 1.8.1

### Smartphone info.

Simulators:
- iPhone 15, iOS 17.4
- iPhone 13, iOS 15.5

Devices:
- iPhone XR, iOS 17.4.1

### Relevant log output

```shell
NSException? "required condition is false: [_nodes containsObject: node]”
```

**Comment by shogo4405** [comment]
Thank you for the report. It has been fixed at https://github.com/shogo4405/HaishinKit.swift/commit/4f2205754f6168f179aa0da96a307f1a68cf7497. Please check it out.

**Comment by mrmda28** [comment]
Thanks for the reply. Unfortunately, this didn't fix the problem.
In the Sources/IO/IOStream.swift file in the func tellyUnit(_ tellyUnit: IOTellyUnit, didSetAudioFormat audioFormat: AVAudioFormat?) method, audioEngine.disconnectNodeInput(tellyUnit.playerNode) creates an exception, and nstry catches it and prints it (as seen in the screenshot).
But in some cases, nstry doesn't catch this exception and a screen freezes because of this. Please run my demo example ([RTMPTest.zip](https://github.com/shogo4405/HaishinKit.swift/files/15486717/RTMPTest.zip)), the screen freezes there (nstry doesn't catch an exception) every time I pause the stream.

<img width="1075" alt="Screenshot 2024-05-29 at 18 03 23" src="https://github.com/shogo4405/HaishinKit.swift/assets/45512200/fb19d2e4-0a17-43c3-a957-b507021e16fc">

**Comment by shogo4405** [comment]
After testing it several times, it did indeed freeze. It seems to be due to running on the main thread. As a workaround, it might be a good idea to wrap it in a Task. 
```
Task {
    stream.close()
}
```

**Comment by shogo4405** [comment]
I am refactoring the code, and the issue no longer occurs on my end with the following changes. How does it work in your environment? The key seems to be the following code.

```swift
Task {
    await self.playerNode.scheduleBuffer(audioBuffer, at: self.audioTime.at)
}
```

**Comment by mrmda28** [comment]
I checked, everything really works very well. Thanks!

**Comment by shogo4405** [comment]
Thank you for the feedback. I would like to release version 1.8.2 around the start of WWDC.
