### ISSUE TITLE
Adaptive bitrate not working

### ISSUE THREAD

**Issue by ArchForge** [shogo4405/HaishinKit.swift#721]
I've implemented the RTMPStreamDelegate for Adaptive Bitrate, but it still seems to be only the frame rate that changes when BW drops. I'm logging the rtmpConnection.currentBytesOutPerSecond, but that never decreases. The didPublish(In)sufficientBW functions are being called as expected. I've pasted my implementation below, if it helps.

    func didPublishInsufficientBW(_ stream: RTMPStream, withConnection: RTMPConnection) {
        adjustBitrate(decrease: true, stream:stream)
    }
    
    func didPublishSufficientBW(_ stream: RTMPStream, withConnection: RTMPConnection) {
        adjustBitrate(decrease: false, stream:stream)
    }

    func adjustBitrate (decrease: Bool, stream: RTMPStream) {
        NSLog("\nHaishin currBitrate: %d", rtmpConnection.currentBytesOutPerSecond);
        if(bitrateCooldown){
            return;
        }
        
        if(decrease){
            if(currentBitrateLevel == .veryVeryBad){    //return if can't go lower
                return;
            }
            if(currentBitrateLevel == .optimal){
                currentBitrateLevel = BitrateLevel(rawValue: currentBitrateLevel.rawValue - 3)!
            }else{
                currentBitrateLevel = BitrateLevel(rawValue: currentBitrateLevel.rawValue - 1)!
            }
            
        }else{
            if(currentBitrateLevel == .optimal){    //return if can't go higher
                return;
            }
            currentBitrateLevel = BitrateLevel(rawValue: currentBitrateLevel.rawValue + 1)!
        }
        
        var newBitrate : UInt32 = 0
        
        switch currentBitrateLevel {
        case .veryVeryBad:
            newBitrate = UInt32(Double(optimalBitrate) * 0.2)   //20%
        case .veryBad:
            newBitrate = UInt32(Double(optimalBitrate) * 0.35)
        case .bad:
            newBitrate = UInt32(Double(optimalBitrate) * 0.5)
        case .almostAcceptable:
            newBitrate = UInt32(Double(optimalBitrate) * 0.7)
        case .acceptable:
            newBitrate = UInt32(Double(optimalBitrate) * 0.8)
        case .almostOptimal:
            newBitrate = UInt32(Double(optimalBitrate) * 0.9)   //90%
        case .optimal:
            newBitrate = optimalBitrate             //100%
        }
        
        if(decrease == false && currentBitrateLevel == .optimal){
            stream.captureSettings[.fps] = 30;
            
        }else if(decrease == true && currentBitrateLevel == .bad){
            stream.captureSettings[.fps] = 25
        }
        
        rtmpStream.videoSettings[.bitrate] = newBitrate
        
        NSLog("\nHaishin newBitrate: %ld", newBitrate)
        NSLog("\nHaishin Bitrate Decrease: %@ newLevel: %ld", decrease.description, currentBitrateLevel.rawValue)
        
        
        let time = decrease ? 5.0 : 3.0;
        
        bitrateCooldown = true
        DispatchQueue.main.asyncAfter(deadline: .now() + time) {
            self.bitrateCooldown = false
        }
    }

I have seen occasional bitrate drops (bitrate + framerate drop) in some live tests (going down in a basement etc.), but usually it only drops the framerate. When testing with network link conditioner, it seems to only ever reduce the framerate.

Additional:
I've left the clear() function empty because I'm not sure what it does. Do you have to do a reconnect after changing the bitrate for it to take effect? I'm using HK v.1.0.9. I'm testing on an iPhone 6+ (iOS 12) and an iPhone 11 Pro (iOS 13)

**Comment by mkrn** [comment]
I've noticed it too. `rtmpStream.videoSettings[.bitrate] = newBitrate`  seems like setting bitrate doesn't always have an effect. The queue might be busy? Would be good to poke at the setter code. This causes issues when someone has bad internet connection but the bitrate doesn't adjust, the FPS is effectively 0. @shogo4405

**Comment by mkrn** [comment]
I believe I fixed it with this setting https://github.com/mkrn/HaishinKit.swift/commit/d232059f83f690fd6f0d69a2437167bf18059d68

**Comment by ArchForge** [comment]
Thanks for investigating. I'm going to run some tests with your fix. Sorry for the late response, I went on vacation. I'll close the issue when/if I can confirm the fix.

**Comment by ArchForge** [comment]
@mkrn I've tested a bit more with your fix, but I still don't see any changes in bitrate. I'm going to try some more stuff tomorrow.

**Comment by ArchForge** [comment]
@mkrn I've tried a some different stuff now in my configuration as well as updating the SDK, but I haven't gotten it to work. My experience with these things is limited, but I read the description of 'kVTCompressionPropertyKey_AverageBitRate', which the SDK seems to use to change the bitrate:

"Note that bit rate settings only have an effect when timing information is provided for source frames, and that some codecs do not support limiting to specified bit rates"

Can this be related to why setting the bitrate doesn't work? And does it have something to do with the .profileLevel setting on rtmpStream.VideoSettings? Because I've changed the profileLevel as the 'default' profile didn't work for me. I'm using kVTProfileLevel_H264_Main_4_0.

**Comment by ArchForge** [comment]
I've mostly gotten the adaptive bitrate to work now, but it's a tricky balance to get right. One of the issues I had was that the bitrate setting seems to not lower the quality if you don't set the bitrate low enough when you get an insufficientBW call. My handling in the code above doesn't work because it ignores the current BW limitation.

Instead, I based my updated bitrate on the currentBytesOutPerSecond parameter when I needed to lower the bitrate. This works much better, but I still have a lot of tweaking to do. Some unrefined code below that might help someone, sometime:

```Swift
private func testBitrateMethod (decrease: Bool) -> UInt32 {
    var newBitrate : UInt32 = 0
    let oldBitrate = rtmpStream.videoSettings[.bitrate] as! UInt32
    let currBytesOut = rtmpConnection.currentBytesOutPerSecond
    
    if(decrease){
        newBitrate = UInt32(Double(currBytesOut) * 0.8)
        
    }else{
        if(oldBitrate < optimalBitrate){
            newBitrate = oldBitrate + UInt32(Double(optimalBitrate) * 0.1)
            
            if(newBitrate > optimalBitrate){
                newBitrate = optimalBitrate;
            }
            
        }else{
            return 0;
        }
    }
    
    return newBitrate
}
```

**Comment by ryango** [comment]
can we disable the frame dropper? seems like it's dropping in response to insuff bandwidth to hit the bandwidth target when I'd rather maintain framerate and decrease bw

**Comment by ryango** [comment]
I guess that doesn't make sense since without adjusting anything else it just is physically incapable of sending more frames so it has to drop them. It just seems that once it starts dropping frames, I get a sufficient BW callback because it's able to send them despite not hitting the bitrate+framerate target.

**Comment by ArchForge** [comment]
@ryango If you lower the bitrate enough on insufficientBW, it won't drop frames. In my implementation, as a safety, I added an FPS-check where I lower the bitrate on sufficientBW if the frame rate is too low. My code is in my previous comment (I go to that code from both suff/insuff with decrease true/false).
